### PR TITLE
Re-implement server-side player name validation

### LINKED ISSUE #106: Custom middleware is broken
In #105, I removed some custom middleware from the server-side code, which did:

- cleanup player names, e.g. remove whitespace, normalize unicode
- validate player name lengths
- check no duplicate player names

The primary issue was that the "hack" of reading the body of the `ctx.req` and then putting the bytes back into the stream doesn't work over the web. This line: https://github.com/kevinddchen/machikoro/blob/3f04230e7f3cad0d9e15eb6690d3515aafd1fea2/src/server/middleware.ts#L24 is not correct for reading the full stream, and we need fancier logic to tell when the stream has ended. We could read the entire stream with something like
```
for await (const chunk in ctx.req) {
    ...
}
```
but then I do not know how to but the bytes back into the stream.

Some possible resolutions:

- Try harder with the hacks, and get something that works both locally and online
- Implement these checks client-side, but this does not guarantee total safety if someone knows how to make malicious API calls
- Try to fix things in the `boardgame.io` repo.

### PR DESCRIPTION
**Pull request by kevinddchen**
This PR is a reattempt of #91, using copied code as a hacky way to get things working. We re-added some functionality removed in #105:

- Leading and trailing whitespace is removed from names.
- Unicode characters are normalized in names.
- Maximum name length is enforced in the server.

This resolves #106.

### CODE REVIEW

File: src/server/patch.ts [hunk 1]
```diff
@@ -0,0 +1,219 @@
+/* eslint-disable */
```
Comment (AquaDragon) [inline src/server/patch.ts:1]: 😂

**Review by AquaDragon — APPROVED** [review]
looks good, seems to be working locally. do we know if it works on the server only when we push it?

**Comment by kevinddchen** [comment]
we can only cross fingers and pray to javascript god(s) it works...
